# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ward}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Anthony Williams"]
  s.date = %q{2010-06-24}
  s.description = %q{Object validation inspired by RSpec.}
  s.email = %q{hi@antw.me}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "History.markdown",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "features/acceptance_matcher.feature",
     "features/attribute_keyword.feature",
     "features/close_to_matcher.feature",
     "features/context_arguments.feature",
     "features/equal_to_matcher.feature",
     "features/error_messages.feature",
     "features/external_validation.feature",
     "features/has_matcher.feature",
     "features/has_matcher_initialized_with_expectation.feature",
     "features/has_matcher_relativities.feature",
     "features/include_matcher.feature",
     "features/is_keyword.feature",
     "features/is_not_keyword.feature",
     "features/match_matcher.feature",
     "features/method_matcher.feature",
     "features/multiple_validators.feature",
     "features/nil_matcher.feature",
     "features/predicate_matcher.feature",
     "features/present_matcher.feature",
     "features/satisfy_matcher.feature",
     "features/scenario_validation.feature",
     "features/step_definitions/external_validation_steps.rb",
     "features/step_definitions/generic_validation_steps.rb",
     "features/step_definitions/object_definition_steps.rb",
     "features/support/env.rb",
     "features/support/object_builder.rb",
     "features/support/struct.rb",
     "lang/en.yml",
     "lib/ward.rb",
     "lib/ward/context.rb",
     "lib/ward/context_chain.rb",
     "lib/ward/dsl.rb",
     "lib/ward/dsl/validation_block.rb",
     "lib/ward/dsl/validation_builder.rb",
     "lib/ward/errors.rb",
     "lib/ward/matchers.rb",
     "lib/ward/matchers/acceptance.rb",
     "lib/ward/matchers/close_to.rb",
     "lib/ward/matchers/equal_to.rb",
     "lib/ward/matchers/has.rb",
     "lib/ward/matchers/include.rb",
     "lib/ward/matchers/match.rb",
     "lib/ward/matchers/matcher.rb",
     "lib/ward/matchers/nil.rb",
     "lib/ward/matchers/predicate.rb",
     "lib/ward/matchers/present.rb",
     "lib/ward/matchers/satisfy.rb",
     "lib/ward/spec.rb",
     "lib/ward/spec/matcher_matcher.rb",
     "lib/ward/support.rb",
     "lib/ward/support/basic_object.rb",
     "lib/ward/support/result.rb",
     "lib/ward/validator.rb",
     "lib/ward/validator_set.rb",
     "lib/ward/version.rb",
     "spec/lib/has_matcher_relativity_examples.rb",
     "spec/lib/have_public_method_defined.rb",
     "spec/rcov.opts",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/ward/context_chain_spec.rb",
     "spec/ward/context_spec.rb",
     "spec/ward/dsl/validation_block_spec.rb",
     "spec/ward/dsl/validation_builder_spec.rb",
     "spec/ward/errors_spec.rb",
     "spec/ward/matchers/acceptance_spec.rb",
     "spec/ward/matchers/close_to_spec.rb",
     "spec/ward/matchers/equal_to_spec.rb",
     "spec/ward/matchers/has_spec.rb",
     "spec/ward/matchers/include_spec.rb",
     "spec/ward/matchers/match_spec.rb",
     "spec/ward/matchers/matcher_spec.rb",
     "spec/ward/matchers/nil_spec.rb",
     "spec/ward/matchers/predicate_spec.rb",
     "spec/ward/matchers/present_spec.rb",
     "spec/ward/matchers/satisfy_spec.rb",
     "spec/ward/matchers_spec.rb",
     "spec/ward/spec/have_public_method_defined_spec.rb",
     "spec/ward/spec/matcher_matcher_spec.rb",
     "spec/ward/validator_set_spec.rb",
     "spec/ward/validator_spec.rb",
     "tasks/features.rake",
     "tasks/rcov.rake",
     "tasks/spec.rake",
     "tasks/yard.rake",
     "ward.gemspec"
  ]
  s.has_rdoc = false
  s.homepage = %q{http://github.com/antw/ward}
  s.post_install_message = %q{************************************************************

Thank you for installing ward-0.1.0

Please note that 0.1 is a preview release and considered
unsuitable for use in a production environment.

************************************************************
}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Ward}
  s.test_files = [
    "spec/lib/has_matcher_relativity_examples.rb",
     "spec/lib/have_public_method_defined.rb",
     "spec/spec_helper.rb",
     "spec/ward/context_chain_spec.rb",
     "spec/ward/context_spec.rb",
     "spec/ward/dsl/validation_block_spec.rb",
     "spec/ward/dsl/validation_builder_spec.rb",
     "spec/ward/errors_spec.rb",
     "spec/ward/matchers/acceptance_spec.rb",
     "spec/ward/matchers/close_to_spec.rb",
     "spec/ward/matchers/equal_to_spec.rb",
     "spec/ward/matchers/has_spec.rb",
     "spec/ward/matchers/include_spec.rb",
     "spec/ward/matchers/match_spec.rb",
     "spec/ward/matchers/matcher_spec.rb",
     "spec/ward/matchers/nil_spec.rb",
     "spec/ward/matchers/predicate_spec.rb",
     "spec/ward/matchers/present_spec.rb",
     "spec/ward/matchers/satisfy_spec.rb",
     "spec/ward/matchers_spec.rb",
     "spec/ward/spec/have_public_method_defined_spec.rb",
     "spec/ward/spec/matcher_matcher_spec.rb",
     "spec/ward/validator_set_spec.rb",
     "spec/ward/validator_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<i18n>, [">= 0.4"])
      s.add_runtime_dependency(%q<activesupport>, [">= 3.0.0.beta"])
      s.add_development_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_development_dependency(%q<cucumber>, [">= 0.3"])
      s.add_development_dependency(%q<yard>, [">= 0.5"])
    else
      s.add_dependency(%q<i18n>, [">= 0.4"])
      s.add_dependency(%q<activesupport>, [">= 3.0.0.beta"])
      s.add_dependency(%q<rspec>, [">= 1.3.0"])
      s.add_dependency(%q<cucumber>, [">= 0.3"])
      s.add_dependency(%q<yard>, [">= 0.5"])
    end
  else
    s.add_dependency(%q<i18n>, [">= 0.4"])
    s.add_dependency(%q<activesupport>, [">= 3.0.0.beta"])
    s.add_dependency(%q<rspec>, [">= 1.3.0"])
    s.add_dependency(%q<cucumber>, [">= 0.3"])
    s.add_dependency(%q<yard>, [">= 0.5"])
  end
end

